# @package _group_
deterministic: false
max_epochs: 1800
min_epochs: 1
resume_from_checkpoint: null
check_val_every_n_epoch: 5
num_sanity_val_steps: 2
accelerator: gpu
precision: bf16
strategy:
  _target_: pytorch_lightning.strategies.DDPStrategy
  find_unused_parameters: true
